---
title: "Data sleuthing notes"
author: "James Clarke"
date: "13 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First of all I want to look at the differences between the data_raw and data_derived files.
Data raw contains three datasets. These include:

*Average annual growth by zone
+includes the zone fish collected in, the associated annual average bottom temperature, estimate of population-wide average growth and the CI's associated with this

*Environmental data
+Includes the zone, it's associated lattitude and longitude, the average annual bottom temperature of each year, total catch in kg (not taking into account fishing effort) and zone specific catch per unit time (CPUE)- this can't be compared across zones as based on deviations from zone average

*tiger flathead data major zones
+Includes zone, batch, fish number and code (all of which can be ignored), the gear type, readability of the otolith, the capture year and month of the fish, port of landing (again ignore), Gender, fish length, age, otolith reader, the edge type of the otolith, radius of otolith, fish ID number, year of spawning, age associated with a particular increment and then the associated increment width and year of this increment. Additionally there is information on whether the individual is a juvenile or adult for a particular increment.

All of these have been assembled in the data derived spreadsheet arranged predominantly by fish ID, including two readings for the water temperature (although both appear to be identical throughout the data), and the logarithmic of the increment width has also been added in this.

#Variables that have continuous measurements for each individual fish
*'Age' -AdjAge possible to use for fixed measures for each fish
*'Year'
*'Increment'
*'CPUE'
*'totalcatch'
*'bottomtemp1' and 'bottomtemp2'
*'growth'
*'log_incr'

All the rest will be common for each fish- therefore make sure to group or you will obtain weird readings. For fish length and age must use AdjAge.


#Some interesting relationships found
+between fish length and radius
+between zones and increment length
+between zones and radius
+between zones and growth
+between zones and floorlength
+between areas and increment length
+between areas and radius
+between areas and growth
+between age and radius
+between age and fishlength
+between age and radius
+no difference between sex and age
+between temperature and growth

Could group by juvenile and adult separately to determine that effect on various relationships.

Extra information on tiger flathead form the Australian governments fishery page(https://www.afma.gov.au/fisheries-management/species/tiger-flathead)

#comments on some categorical variables

+zone
Four zones. EBS, ETAS, NSW, WTAS.
The majority of the data is obtained from the EBS zone

+gear
Two types. Danish seine and trawl.
The majority is carried out by trawling.
501 unknown values also.

+sex
most have positive gender ID. 3804 unknown however.

+reader
5 different readers. The most common reader was Simon.

+edge type
most common are blank, 1, n or w. Very few are '4'.

+maturity
As mentioned by fede in his explanatory notes, juveniles seem to be categorised as all ages below 5 years old. However, the website says this species will reach sexual maturity between 3-5 years?? Fede didn't really use this variable though.

#Some comments on continuous variables
+For growth, upper and lower there are a total of 6 missing values

+The latest record that we have is from 1971, although the mean is 2001. Latest is 2009.

+Increment. Some potential outliers. Max is 0.877 but mean is 0.21414.

+Fish length- max is 65, mean 40.12, min is 20. 72 missing values. Website says that they grow up to 70cm, and that females are generally larger than males.

+Age- website says they live up to 15 years and that females live longer than males. Apparantly in the adjusted age section the max value is 28. This seems unlikely though, however, in the notes it is said that this otolith is huge(although the fish length was not the biggest), it is also carried out by Simon, who is the most common reader. The next oldest is 25 and it has been noted for this one that it was difficult to read this otolith. Not sure where they get these values from the Age section though as only 15 increments were counted for the 28 year old fish and only 10 counted for the 25 year old one. Mean for AdjAge is 6.712. and min is 2 years old.

