---
title: "Mathematical notation"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

**model 1**


$y_{i} = \alpha + \beta x_{i} + \epsilon$ 

***************
**model 2**


$y_{i} = \alpha_{j \left[{i}\right]} + \beta x_{i} + \epsilon$

***************
**model 3**


$y_{i} = \left(\alpha_{1} +  \beta x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2} +  \beta x_{i}\right)\tau_{i} + \epsilon $


$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{i}\right)}}$


***************
**model 4**


$y_{i} = \left(\alpha_{1_{{j}\left[{i}\right]}} +  \beta x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2_{{j}\left[{i}\right]}} +  \beta x_{i}\right)\tau_{i} + \epsilon $

$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{i}\right)}}$

**************
**model 5**

$y_{i} = \left(\alpha_{1} +  \beta x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2} +  \beta x_{i}\right)\tau_{i} + \epsilon $

$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{{j\left[{i}\right]}}\right)}}$

**************
**model 6**


$y_{i} = \left(\alpha_{1_{{j}\left[{i}\right]}} +  \beta x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2_{{j}\left[{i}\right]}} +  \beta x_{i}\right)\tau_{i} + \epsilon $

$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{{j\left[{i}\right]}}\right)}}$

***************
**model 7**

$y_{i} = \alpha + \beta_{1} x_{i} + \beta_{2} \left(x_{i} - \eta\right) \tau_{i} + \epsilon$



$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{i}\right)}}$


***************
**model 8**


$y_{i} = \alpha_{j \left[{i}\right]} + \beta_{1} x_{i} + \beta_{2} \left(x_{i} - \eta\right) \tau_{i} + \epsilon$



$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{i}\right)}}$

****************
**model 9**


$y_{i} = \alpha + \beta_{1} x_{i} + \beta_{2} \left(x_{i} - \eta_{j \left[{i}\right]}\right) \tau_{i} + \epsilon$



$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{{j\left[{i}\right]}}\right)}}$


*****************
**model 10**

$y_{i} = \alpha_{j\left[{i}\right]} + \beta_{1} x_{i} + \beta_{2} \left(x_{i} - \eta_{j \left[{i}\right]}\right) \tau_{i} + \epsilon$



$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{{j\left[{i}\right]}}\right)}}$


******************
**model 11**

$y_{i} = \left(\alpha_{1} +  \beta_1 x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2} +  \beta_2 x_{i}\right)\tau_{i} + \epsilon $


$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{i}\right)}}$


******************
**model 12**

$y_{i} = \left(\alpha_{1_{{j}\left[{i}\right]}} +  \beta_1 x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2_{{j}\left[{i}\right]}} +  \beta_2 x_{i}\right)\tau_{i} + \epsilon $

$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{i}\right)}}$

******************
**model 13**

$y_{i} = \left(\alpha_{1} +  \beta_1 x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2} +  \beta_2 x_{i}\right)\tau_{i} + \epsilon $

$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{{j\left[{i}\right]}}\right)}}$

******************
**model 14**

$y_{i} = \left(\alpha_{1_{{j}\left[{i}\right]}} +  \beta_1 x_{i}\right) \left(1 - \tau_{i}\right) +  \left(\alpha_{2_{{j}\left[{i}\right]}} +  \beta_2 x_{i}\right)\tau_{i} + \epsilon $

$\tau_{i} = \frac{1}{1 + e^{-100\left(x_{i} - \eta_{{j\left[{i}\right]}}\right)}}$